[package]
name = "hmda_lib"
version = "0.1.0"
authors = ["Juan Marin Otero <juan.marin.otero@gmail.com>"]

[dependencies]
hyper = "0.11.25"
tokio-core = "0.1"
futures = "0.1"
hyper-tls = "0.1.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
num_cpus = "1.0"
